---
title: "Various info"
author: "Owen"
date: "2/6/2017"
output: html_document
---

This webpage is information for content creators, instructors, and TAs.

This webpage is associated with a [github repo](https://github.com/opetchey/BIO144), where things such as datasets, pdfs (and code for) lectures, and other resources are held.

The github repo also has an issue tracker. Please use it as you like.

Students don't need to look at this page, and we don't make them aware of it. It is public however, so please do not add any sensitive information, such as personal information about students, or any information related to examination questions and answers

The students use the course via [OpenEdX\@UZH](https://openedx.mnf.uzh.ch/courses/course-v1:UZH+BIO144+FS2017/info).


## Weekly structure on OpenEdX\@UZH

Each week as at least one of the following sections (BC = before class; IC = in class):

* Important info.
* BC content
* IC Practical exercises
* IC Lecture
* Extras
* Graded assessment


## Students on the course

Available from the Dozierendenportal:
https://idared.uzh.ch/irj/portal
There, is an up-to-date list of all registrations for each group, including email addresses, to download or send an email directly.

The registration window closes Feb 12 (2017), so on Feb 13 you should have the maximum number of participants.
Also, most students are visible in OLAT. For some strange reason, the two lists do not completely coincide. The Dozierendenportal is the “true list”.

Students that miss the deadline for registering should contact the studienkoordination\@biol.uzh.ch


## Timeline 2017

- 20.1 TA meet and greet
- 13.2 TA briefing
- 12.2 Student registration closes 12.2
- 13.2 Students emailed to go to OpenEdX\@UZH 
- 23.2 First day of course
- 2.5  Stornierungsfrist (drop course deadline)
- Formal feedback: Studienangebotsentwicklung
- 13.6 Final exam: 14-16h
- Grades should go into the system asap.
- Students allowed to view their paper (one afternoon / day to come see me)
- Submit any grade alterations
- 20.7 Validation of exam
- September: Repetition exam??? 

- Weekly progress check all students.
- Daily check of Discussion forums.


