# Course reading materials and other resources {-}

The course will assign reading from a variety of sources, with that reading being specified each week. Sometimes reading will be replace or be accompanied by viewing video lectures. Some of the reading / viewing will be core (i.e., required) and some will be optional. Only the material in the core reading / viewing will be examined directly; familiarity with material in the optional reading / viewing will not hurt.

Textbooks with required or optional reading are in the main library, and should be accessible electronically through the main library.

Some books are available online via the UZH library. Access to these is only possible within the IP range of the UZH. You have only access with LAN or WLAN UZH and with VPN UZH.

Core reading will come from various sources, including two textbooks:

* *Getting Started with R, An introduction for biologists* (2017, Second Edition) Beckerman, Childs & Petchey (**DO NOT USE THE FIRST EDITION!**)

* *The New Statistics with R, An Introduction for Biologists* (2015, First Edition) Hector. [Ebook via UZH library.](http://ezproxy.uzh.ch/login?url=http://dx.doi.org/10.1093/acprof:oso/9780198729051.001.0001)

Optional reading will come from various sources, including these textbooks:

* *Regression; Models, Methods and Applications* (2013 Edition) Fahrmeir, Kneib, Lang & Marx.

* *The Analysis of Biological Data* (2015, Second Edition) Whitlock & Schluter.

* *The Essential Guide to Effect Sizes. Statistical Power, Meta-Analysis, and the Interpretation of Research Results (2010, First Edition) Ellis. [Ebook via UZH library.](http://ezproxy.uzh.ch/login?url=http://dx.doi.org/10.1017/CBO9780511761676)

* *Statistics: An Introduction using R* (2011, Second Edition) Crawley.

Other reading:

* http://r4ds.had.co.nz
* http://dzchilds.github.io/aps-data-analysis-L1/
* http://dzchilds.github.io/aps-data-analysis-L2/
* https://geanders.github.io/RProgrammingForResearch/index.html
