# Expected competencies {-}

Many of you already have skills and knowledge important for data analysis in biology. Below we cover what you're expected to already know, from previous learning (in particular [From MAT183 - Stochastik für die Naturwissenschaften] and [From BIO134 - Programming in Biology]).

You will greatly benefit from having reasonable recall of this material. So, before the first class:

1. Take the [expected competencies self-test](https://openedx.mnf.uzh.ch/courses/course-v1:UZH+BIO144+FS2017/courseware) in OpenEdX.
2. Based on your self-test of expected competencies, review material from previous courses. I.e. review the stuff you can't remember! 
3. If you feel like you need an R / RStudio refresher, or need help install them, have a look at the following material.

## Information on installing R and RStudio {-}

* Video lecture: [Installing R and RStudio on a Mac.](https://youtu.be/wdO3EpEkj-E)
* Video lectures: Installing R and RStudio on Windows, [part 1](https://youtu.be/ubanYI79jqs) and [part 2](https://youtu.be/DVw5dD_SdEo).
* Video lecture: [Installing R on Linux.](https://youtu.be/mtpaKpMNHn4) (Not for the faint hearted, and you will still need to install RStudio.)

Reading: Chapter 1, Getting and getting acquainted with R, in Getting Started with R, an Introduction for Biologists, by Beckerman, Childs, & Petchey.

## Information about getting acquainted with R {-}

* Video lecture: [Starting R, Some basic arithmetic in R, writing a script, and submitting commands to the Console.](https://youtu.be/5rxRbpFVXiA)
* Video lecture: [Saving your script file, and few other things to make your R-life easier.](https://youtu.be/58_lmh-ETP4)
* Video lecture: [The assigment arrow, and working with vectors](https://youtu.be/yTMLPPiCbzY)
* Video lecture: A simple graph with R. (Link to be added later.)

## Reading instead of video lectures {-}

Most of what's covered in the video lectures is in **Chapter 1, Getting and getting acquainted with R**, in [Getting Started with R, an Introduction for Biologists, by Beckerman, Childs, & Petchey.](link_to _be_added)





## From MAT183 - Stochastik für die Naturwissenschaften {-}

* Methods for describing characteristics of some data. For example, measures of where the centre of the data is, e.g., mean, median, mode. And measures of the spread of the data, e.g. quartiles, variance, standard deviation, standard error. And measures of how symetric is the spread, e.g. the skew of the data.

* Basic use of R and RStudio. Including, basic arithmetic in R, on scalars and vectors. Use of logical operators (i.e. <, >, ==, !, &, |); Importing data into R; Getting a basic summary information about your data in R, e.g., mean, median, variance, standard deviation.

* Basic probability. For example, what is the probabiliy of getting five heads if we toss a fair coin seven times? What is the probability that given a couple has three children, that at least two are boys.

* You should be aware of the importance of and characteristics of a few probability distributions: normal, binomial, poisson, exponential. Many methods of data analysis require at least a basic understanding of such distributions. You have worked with these distributions in R, using functions such as `dnorm()`, `pnorm()`, `qnorm()`. and `rnorm()`.

* Frequency distributions and histograms are important for visualising the distribution of your data. You should know what these are, and how to make them in R, for example using the `hist()` function.

* As well as making histograms in R, making box and whisker plots, making qq-plots, and making bivariate scatter plots. Also, how to make R plot mathematical functions (e.g., $y=exp(x)$ and $y=sin(x)$).

* The statistical concepts: *expectations*, *parameters*, *parameter estimates*, *the central limit theorem*, *hypothesis testing*, and *standard error of the mean*.

* A few basic statistical tests: the one- and two-sample *t*-tests; the $\chi^2$-test. You should know when to use them, what they can tell us, and how to implement them in R.



## From BIO134 - Programming in Biology {-}

In BIO134 you spent a lot of time learning concepts and practices about programming, and in that class you used the programming language *Python*. In BIO144 you will use a different language, called *R* via *RStudio*; you used this already in MAT183. There are lots of similarities between Python and R, so please think about applying what you learned in BIO134 in this class (there are also difference, so don't expect your Python code to work in R!). For example, you will benefit from recalling what you learnt about: functions, strings, files, plotting, and data analysis: Spearman correlation.




