--- 
title: "BIO144 -- Data Analysis for Biologists"
author: "Owen L. Petchey & Stefanie Muff"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: opetchey/bio144
description: "This is the information for BIO144"
---

# About the course {-}

## Course aims and learning outcomes  {-}

This course will help you develop a solid foundation in answering biological questions with quantitative data. The approaches you will learn are, however, generally applicable to using data to solve problems, an increasing important skill in a world more and more dominated by data.

By the end of the course you will be able to:

* Plan how to make use quantitative data to solve a biological problems.
* Translate a biological question into a quantitative problem.
* Collect and arrange data for efficient processing.
* Reliably, accurately and efficiently manage and manipulate data.
* Make clear and informative visualisations of data.
* Select, perform, validate, and interpret an appropriate statistical test / model.
* Understand why and when linear models are useful, and what to do when they are not.
* Clearly communicate the answer to your biological question.
* Research and learn about other tools for data analysis


## Your instructors {-}

Your instructors for this course are [Prof. Owen Petchey](http://www.ieu.uzh.ch/en/staff/professors/petchey.html) and [Dr. Stefanie Muff](http://www.ebpi.uzh.ch/en/aboutus/departments/biostatistics/teambiostats/muff.html).

Prof. Petchey has been investigating how environmental change affects ecological communities, using a combination of empirical and mathematical methods (including lots of analysis of data) for going on 20 years. He specialises in the practical side of data analysis, in particular, how to implement them in the R software that will be used extensively in this course.

Dr. Muff is a mathematician and statistician, working in the across fields of biology, developing better methods for analysing data.

Your teaching assistants will be listed here at a later date.

## Course schedule {-}

```{r, echo=FALSE}
schedule <- read.csv("assets/schedule.csv")
knitr::kable(schedule, col.names = c("Week", "Dates", "Practical (1-3pm)", "Lecture (3-5pm)"))
```



## You will need to use two websites {-}

This one, and the OpenEdX\@UZH learning platform.

Use this site as a guide through the course, with week-by-week schedule of content and activities.

You will use [OpenEdX\@UZH](https://openedx.mnf.uzh.ch/courses/course-v1:UZH+BIO144+FS2017/about) for four things:

1. To take the **assessments** that occur during the course
2. To **view video lectures**.
3. To recieve **important messages** about the course.
3. For **discussing and communicating** all and anything about the course.


## How to get help {-}

We aim that you can ask for help about anything and get a useful answer as soon as possible. The following guidelines will help you get fast, useful help.

1. Sending emails to course staff will result in you receiving no, slow or perhaps not so useful advice (i.e., please come see me during the class).
2. Please think about if other students might benefit from knowing the answer to your question. Its very likely that other students are wondering the same thing as you. In that case, it is great if you ask the question in a public / class forum. One such place is the OpenEdX discussion forum, another is during class when questions are actively encouraged.
3. If knowing the answer to your question is not going to help other students (perhaps it might be about your personal circumstances), then approach and talk with a TA, Dr Muff, or Prof. Petchey in class. We will reserve some class time for these types of question.


## When and where is the course held? {-}

The course runs during the whole 14 week spring semester, though there will be no "in-person" time during two of these weeks, due to holidays.

You will attend class on either Thursday or Friday afternoon, 1-5pm. *You will be assigned to an afternoon, based on your other class commitments. CHECK THIS*

All classes will be held in **Y24-G-45**.


## You will need to use your own laptop during the course {-}

Please bring your laptop to class. Please make sure that it has sufficient battery charge to last the duration of the class, as there are few power sockets in **Y24-G-45**. Please make sure you know how to use it (some people are sometimes not so sure, perhaps because its new, or they borrow someone else's.) Your laptop must be able to connect to the wireless internet at UZH, and you will need two software programmes (see section [Setting up your laptop]).


## Course structure {-}

The course is composed of two sides: the more **conceptual side** and the more **practical side**.

The conceptual side will be composed of lectures mostly delivered by Dr. Muff, 1-3pm.

The practical side of the course will use a “flipped classroom” approach: you do the lectures / reading at home (or anywhere you like) and you do the "homework" during the practical class. The practical classes will be overseen by TAs and Prof. Petchey. 3-5pm.


## Assessment {-}

There will be three assessment-related activities:

1. Each week there will be questions about the class on OpenedX. You must answer 80% of these questions correctly in order to be permitted to sit the final assessment.
2. A mid-semester assessment, which will not contribute to your final grade. The aims of this are to help you understand if you are effectively learning the required material, to give you practice with the types of questions that will be in the final examination. This mid-semester examination will be conducted during one of the usual afternoon classes. During the first two hours (1-3pm) you will sit the exam, and during the second two hours (3-5pm) you will grade your own exam paper against solutions presented by an instructor.
3. A final assessment during the module examination period in July. Exact date and location to be confirmed.


## Being ready for class {-}

The practical side of the course uses a “flipped classroom” approach: you do the lectures / reading at home (or anywhere you like) and you do the homework in class. The homework is practical exercises, working with data on your computer.

### What am I expected to already know? {-}

Please see the relevant sections in the [Expected competencies] page (i.e., the two sections labelled "Expected competencies from previous courses", one of which is conceptual competencies, and the other practical).

### What must I do before each practical class? {-}

You must complete the assigned required reading / viewing. This material is essential and will not be covered during class (lecture or practical). If you do not complete the assigned reading you will have great trouble with the practical exercises, and with answering the weekly practical related questions correctly. Answering 80% or more of these questions correctly is required to be permitted to sit the final exam. Feel free to attempt the practical exercises before class.

### Where can I find the weekly assigned reading / viewing? {-}

This is given below, in the section for the week you are approaching.


## Course reading materials and other resources {-}

The course will assign reading from a variety of sources, with that reading being specified each week. Sometimes reading will be replace or be accompanied by viewing video lectures. Some of the reading / viewing will be core (i.e., required) and some will be optional. Only the material in the core reading / viewing will be examined directly; familiarity with material in the optional reading / viewing will not hurt.

Textbooks with required or optional reading are in the main library, and should be accessible electronically through the main library.

Some books are available online via the UZH library. Access to these is only possible within the IP range of the UZH. You have only access with LAN or WLAN UZH and with VPN UZH.

Core reading will come from various sources, including two textbooks:

* *Getting Started with R, An introduction for biologists* (2017, Second Edition) Beckerman, Childs & Petchey (**DO NOT USE THE FIRST EDITION!**)

* *The New Statistics with R, An Introduction for Biologists* (2015, First Edition) Hector. [Ebook via UZH library.](http://ezproxy.uzh.ch/login?url=http://dx.doi.org/10.1093/acprof:oso/9780198729051.001.0001)

Optional reading will come from various sources, including these textbooks:

* *Regression; Models, Methods and Applications* (2013 Edition) Fahrmeir, Kneib, Lang & Marx.

* *The Analysis of Biological Data* (2015, Second Edition) Whitlock & Schluter.

* *The Essential Guide to Effect Sizes. Statistical Power, Meta-Analysis, and the Interpretation of Research Results (2010, First Edition) Ellis. [Ebook via UZH library.](http://ezproxy.uzh.ch/login?url=http://dx.doi.org/10.1017/CBO9780511761676)

* *Statistics: An Introduction using R* (2011, Second Edition) Crawley.

Other reading:

* http://r4ds.had.co.nz
* http://dzchilds.github.io/aps-data-analysis-L1/
* http://dzchilds.github.io/aps-data-analysis-L2/
* https://geanders.github.io/RProgrammingForResearch/index.html


## How to give feedback about the course {-}

Your views on the course are really important to us. What works well, what doesn't work so well, what content is particularly important, what content is not so important, what content is missing?

There are several ways of providing feedback.

1. During the course, you can tell us in person during class, and can make posts on the Discussion forum. Such feedback during the course has the potential to improve the course for you. I.e. we might be able to change something quickly, so your and your fellow students'  experience of the class is improved.

2. Submit a comment, which can be anonymous, via a google form. Details to be confirmed. 

3. Fill in the "official" course evaluation form. Details to be confirmed.

