# Week 1  - Introduction and more {-}

## During class {-}

Week 1 is a little different from all subsequent weeks, as we are getting started. While all subsequent weeks are the practical session 1-3pm and lecture session 3-5pm, in week 1 things are a bit mixed up.

### Why is data analysis so important? {-}

The course will begin with a general introduction, including why data analysis is so important in biology and biomedicine, and indeed in many walks of life and careers. We will introduce a few problems that can be addressed by anaylsis of data, including:

* In order to conserve and manage species, and potentially assist them adapt to environmental change, we need to know their habitat requirements. This problem, and the role of data analysis, is illustrated by a study of otter populations in the European Alps.

* In small populations, or populations that have been small (i.e. experienced a bottleneck), closely related individual may mate and have offspring. Such inbreeding can have fitness costs that may endanger population persistence. The consequence of inbreeding among alpine ibex. This problem is illustrated by a quantitative study of Apline ibex populations.

* Mercury can be quite toxic, with potentially nasty effects on people's health. It can also occur in the environmentl Quantitative analyses can help understanding links between amounts of mercury in the environment and inside people's bodies. This problem is illustrated by a study in the Wallis.

* Physical activity (exercise) can be mentally and physically beneficial. Knowing the factors that influence physical activity could be useful for developing policies to encourage and promote it. This problem is illustrated by a study that recorded children's activity patterns, and also recorded information about their lives, such as media consumption and behaviour of parents.

In addition, you're introduced to some problems (and their associated datasets) that we use several times during the course:

* A study of predictors of body fat in humans.

* A study of diet and blood glucose levels.

* A study of use of blood screening to indicate certain diseases.

Nevertheless, many other problems and datasets will be introduced and used during the course.


### Some important terms {-}

We'll explain what we mean by data analysis, statistical analysis, models, and some other important terms.


### A general workflow for data analysis {-}

We'll introduce a general workflow that we'll use for all the data analyses in the course.


### Data wrangling {-}

There will be a brief introduction to data wrangling, and you will be directed to the study you will do before the week 2 practical session.

### Visualisation of data  {-}

Visualising our data in graphs is one of the most important parts of data analysis. We use it to explore our data, to understand our data, to guide our statistical analyses, and to communicate our results. There will be a brief introduction to types of graphs to use (and not to use). You will be directed to the study you will do before the week 2 practical session.

### Live data analysis demonstration {-}

We will attempt to go through the entire workflow during the class! This will be a good opportunity to recap some of the things you should already know.


## Study to do by week 2 {-}

Watch the video lectures "Getting data ready for R", "Getting data into R", and "Basic visualisation in R".

Read chapters X, Y, and Z of ???BOOK???.

Consider attempting the exercises for the week 2 practical session.


## Handouts {-}

[PDF of the lecture by Dr. Muff.](\lectures\week1\en\lecture1_en.pdf)

## Further reading {-}


