---
title: "Histograms and QQ-plots"
author: "Owen"
date: "1/17/2017"
output: 
  pdf_document: 
    number_sections: yes
    toc: yes
---

```{r, echo=FALSE, message=F, warning=FALSE}
library(tidyverse)
```


# Normal distribution
```{r,echo=FALSE,out.width='.49\\linewidth', fig.width=3, fig.height=3}
x <- rnorm(100)
qplot(x, bins=30)
qqnorm(x)
qqline(x)
```


# Uniform distribution
```{r,echo=FALSE,out.width='.49\\linewidth', fig.width=3, fig.height=3}
x <- runif(100)
qplot(x, bins=30)
qqnorm(x)
qqline(x)
```


# A left skewed distribution
```{r,echo=FALSE,out.width='.49\\linewidth', fig.width=3, fig.height=3}
x <- rbeta(100,5,2)
qplot(x, bins=30)
qqnorm(x)
qqline(x)
```


# A right skewed distribution
```{r,echo=FALSE,out.width='.49\\linewidth', fig.width=3, fig.height=3}
x <- rbeta(100,2,5)
qplot(x, bins=30)
qqnorm(x)
qqline(x)
```



# A log-normal distribution
```{r,echo=FALSE,out.width='.49\\linewidth', fig.width=3, fig.height=3}
x <- rlnorm(100)
qplot(x, bins=30)
qqnorm(x)
qqline(x)
```


# Poisson distribution
```{r,echo=FALSE,out.width='.49\\linewidth', fig.width=3, fig.height=3}
x <- rpois(100, lambda=2)
qplot(x, bins=30)
qqnorm(x)
qqline(x)
```


# Binomial distribution
```{r,echo=FALSE,out.width='.49\\linewidth', fig.width=3, fig.height=3}
x <- rbinom(100, size=10, p=0.2)
qplot(x, bins=30)
qqnorm(x)
qqline(x)
```

